#!/bin/bash
wkhtmltopdf --javascript-delay 800 \
http://gordonguthrie.github.io/TheManual \
https://gordonguthrie.github.io/TheManual/for_reviewers/for_first_timers.html \
https://gordonguthrie.github.io/TheManual/for_reviewers/for_developers.html \
https://gordonguthrie.github.io/TheManual/chapter1/introduction.html \
https://gordonguthrie.github.io/TheManual/chapter1/installing_supercollider.html \
https://gordonguthrie.github.io/TheManual/chapter1/first_beep_in_supercollider.html \
https://gordonguthrie.github.io/TheManual/chapter1/first_synth_in_sonic_pi.html \
https://gordonguthrie.github.io/TheManual/chapter1/setting_up.html \
https://gordonguthrie.github.io/TheManual/chapter2/the_synths.html \
https://gordonguthrie.github.io/TheManual/chapter2/overtone_synths.html \
https://gordonguthrie.github.io/TheManual/chapter2/supercollider_synths.html \
https://gordonguthrie.github.io/TheManual/chapter3/deep_dive.html \
https://gordonguthrie.github.io/TheManual/chapter3/investigating_sonic_pi_and_error_messages.html \
https://gordonguthrie.github.io/TheManual/chapter3/loggin_loggin_loggin.html \
https://gordonguthrie.github.io/TheManual/chapter3/how_synthdefs_are_loaded.html \
https://gordonguthrie.github.io/TheManual/chapter3/how_sonic_pi_plays_synths.html \
https://gordonguthrie.github.io/TheManual/chapter4/how_built_in_synths_are_defined_in_Sonic_Pi.html \
https://gordonguthrie.github.io/TheManual/chapter4/the_synth_beep.html \
https://gordonguthrie.github.io/TheManual/chapter5/planning_our_new_synth.html \
https://gordonguthrie.github.io/TheManual/chapter5/the_development_cycle.html \
https://gordonguthrie.github.io/TheManual/chapter5/funky_stuff_part_uno_variables.html \
https://gordonguthrie.github.io/TheManual/chapter5/compile_errors.html \
https://gordonguthrie.github.io/TheManual/chapter5/ugens_channels_mixing_and_panning.html \
https://gordonguthrie.github.io/TheManual/chapter5/mysecondsynth_supercollider.html \
https://gordonguthrie.github.io/TheManual/chapter5/mysecondsynth_ruby.html \
https://gordonguthrie.github.io/TheManual/chapter5/mysecondsynth_sonic_pi.html \
https://gordonguthrie.github.io/TheManual/chapter5/mythirdsynth_supercollider.html \
https://gordonguthrie.github.io/TheManual/chapter5/mythirdsynth_ruby.html \
https://gordonguthrie.github.io/TheManual/chapter5/mythirdsynth_sonic_pi.html \
https://gordonguthrie.github.io/TheManual/chapter5/the_env_ugen.html \
https://gordonguthrie.github.io/TheManual/chapter5/myfourthsynth_supercollider.html \
https://gordonguthrie.github.io/TheManual/chapter5/myfourthsynth_ruby.html \
https://gordonguthrie.github.io/TheManual/chapter5/myfourthsynth_sonic_pi.html \
https://gordonguthrie.github.io/TheManual/chapter5/moar_ugen_stuff.html \
https://gordonguthrie.github.io/TheManual/chapter5/your_first_synth.html \
https://gordonguthrie.github.io/TheManual/chapter6/whats_next.html \
the_manual.pdf
